In [1]:
import numpy as np
import pandas as pd

# Data Types and attributes

In [2]:
#numpy main data type is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
a2 = np.array([[1,2,3.9],
              [4,5,6.5]])
a2

array([[1. , 2. , 3.9],
       [4. , 5. , 6.5]])

In [4]:
a3 = np.array([[[1,2,3],
              [4,5,6],
               [7,8,9],
               [10,11,12],
               [13,14,15],
               [16,17,18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [5]:
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (1, 6, 3))

In [6]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [7]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [8]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [9]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [10]:
#creating a dataframe from a np array

import pandas as pd

df =pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.9
1  4.0  5.0  6.5

# Creating arrays`

In [11]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [12]:
sample_array.dtype

dtype('int64')

In [13]:
ones = np.ones((2, 4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
type(ones)

numpy.ndarray

In [15]:

ones.ndim

2

In [16]:
ones.dtype

dtype('float64')

In [17]:
ones.size

8

In [18]:
zeros = np.zeros((2,4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [19]:
range_array = np.arange(5, 30, 5)
print(range_array)

[ 5 10 15 20 25]


In [60]:
random_array1 = np.random.rand(5,3)
random_array1

array([[0.55642943, 0.15986708, 0.14382937],
       [0.64946303, 0.5392236 , 0.32568477],
       [0.14701389, 0.15987007, 0.12941234],
       [0.57892239, 0.09226017, 0.91054472],
       [0.08297175, 0.80037846, 0.87713097]])

In [21]:
random_array2 = np.random.randint(2,5, size =(5,4))
random_array2

array([[4, 2, 3, 3],
       [4, 3, 2, 2],
       [4, 2, 4, 2],
       [3, 3, 4, 3],
       [2, 4, 4, 4]])

In [22]:
type(random_array2)

numpy.ndarray

In [23]:
random_array2.dtype

dtype('int64')

In [24]:
random_array2.shape

(5, 4)

In [25]:
random_array3 = np.random.random((3, 4))
random_array3

array([[0.71027438, 0.48590858, 0.18854955, 0.9440589 ],
       [0.8827876 , 0.47126462, 0.75571441, 0.21913831],
       [0.5314707 , 0.46710971, 0.43220213, 0.85996523]])

In [26]:
#pseudo random nums
np.random.seed(seed =0)
random_array4 = np.random.randint(12, size =(5,4))
random_array4

array([[ 5,  0,  3, 11],
       [ 3,  7,  9,  3],
       [ 5,  2,  4,  7],
       [ 6,  8,  8, 10],
       [ 1,  6,  7,  7]])

# Viewing arrays and Metrices

In [27]:
np.unique(random_array4)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
a1

array([1, 2, 3])

In [29]:
a2

array([[1. , 2. , 3.9],
       [4. , 5. , 6.5]])

In [30]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [31]:
a1[0]

1

In [32]:
a2.shape


(2, 3)

In [33]:
a2[1]

array([4. , 5. , 6.5])

In [34]:
a3.shape

(1, 6, 3)

In [35]:
a3[:2, :2, :2]

array([[[1, 2],
        [4, 5]]])

In [36]:
a4 =np.random.randint(15, size=(2,6,9, 6))
a4

array([[[[14,  8,  1,  5,  9, 13],
         [ 8,  9,  4,  3,  0,  3],
         [ 5, 14,  0,  2,  3,  8],
         [ 1,  3, 13,  3,  3, 14],
         [ 7,  0,  1,  9,  9,  0],
         [10,  4,  7,  3, 14, 11],
         [ 2,  7, 12,  2,  0,  0],
         [ 4,  5,  5,  6,  8,  4],
         [ 1,  4,  9, 10, 10,  8]],

        [[ 1,  1,  7,  9,  9,  3],
         [ 6,  7, 11, 14,  2, 11],
         [ 0, 14,  3,  5, 12,  9],
         [10,  4, 11,  4,  6,  4],
         [ 4,  3, 12,  4,  4,  8],
         [14,  4,  3, 10,  7, 13],
         [ 5,  5,  0,  1,  5,  9],
         [ 3,  0,  5, 14,  0,  1],
         [ 2,  4,  2,  0, 13,  3]],

        [[ 2, 10, 13,  0,  7,  5],
         [ 9,  0, 10,  2, 11, 10],
         [ 7, 11,  2,  9,  2, 14],
         [ 3, 14, 11,  3,  2, 14],
         [ 3,  4,  1,  2, 11, 14],
         [ 9, 10,  1,  4, 10,  6],
         [11,  8, 11,  2,  3,  0],
         [ 0,  6,  0,  6,  3, 14],
         [10,  3,  8, 12,  8, 13]],

        [[14,  8, 13,  2,  3, 14],
         [ 2, 

In [37]:
a4.shape, a4.ndim

((2, 6, 9, 6), 4)

In [38]:
#Get the first 4 nums in the inner most array
a4[:, :, :, :4]

array([[[[14,  8,  1,  5],
         [ 8,  9,  4,  3],
         [ 5, 14,  0,  2],
         [ 1,  3, 13,  3],
         [ 7,  0,  1,  9],
         [10,  4,  7,  3],
         [ 2,  7, 12,  2],
         [ 4,  5,  5,  6],
         [ 1,  4,  9, 10]],

        [[ 1,  1,  7,  9],
         [ 6,  7, 11, 14],
         [ 0, 14,  3,  5],
         [10,  4, 11,  4],
         [ 4,  3, 12,  4],
         [14,  4,  3, 10],
         [ 5,  5,  0,  1],
         [ 3,  0,  5, 14],
         [ 2,  4,  2,  0]],

        [[ 2, 10, 13,  0],
         [ 9,  0, 10,  2],
         [ 7, 11,  2,  9],
         [ 3, 14, 11,  3],
         [ 3,  4,  1,  2],
         [ 9, 10,  1,  4],
         [11,  8, 11,  2],
         [ 0,  6,  0,  6],
         [10,  3,  8, 12]],

        [[14,  8, 13,  2],
         [ 2, 11, 13,  0],
         [ 3,  8, 10,  2],
         [ 3, 12, 13, 14],
         [ 3, 13, 11, 12],
         [ 9, 13, 11,  8],
         [13,  5, 14,  9],
         [ 9,  6,  5, 13],
         [ 8,  0,  4, 11]],

        [[ 6,  5, 13

In [39]:
#Math
a1

array([1, 2, 3])

In [40]:
ones =np.ones(3)
ones

array([1., 1., 1.])

In [41]:
a1 - ones

array([0., 1., 2.])

In [42]:
a1 * ones

array([1., 2., 3.])

In [43]:
a1 * a2

array([[ 1. ,  4. , 11.7],
       [ 4. , 10. , 19.5]])

In [44]:
#floor division removes the decimals. Rounds down
a2//a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [45]:
a2/a1

array([[1.        , 1.        , 1.3       ],
       [4.        , 2.5       , 2.16666667]])

In [46]:
#raise the power
a2**2

array([[ 1.  ,  4.  , 15.21],
       [16.  , 25.  , 42.25]])

In [47]:
np.square(a2)

array([[ 1.  ,  4.  , 15.21],
       [16.  , 25.  , 42.25]])

In [48]:
np.add(a1, ones)

array([2., 3., 4.])

In [49]:
#modular show the remainder when divided
a1 % 2

array([1, 0, 1])

In [50]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [51]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

# Aggregation


In [52]:
#Performing the same number of operations on the same things
listy_list=[1,2,3]

In [53]:
sum(listy_list)

6

In [54]:
sum(al)

NameError: name 'al' is not defined

In [ ]:
np.sum(a1)

 Use python methods(sum()) on python datatypes and Numpy methods on numpy arrays(np.sum())


In [ ]:
# create a massive numpy array
massive_array = np. random.random(100000)
massive_array.size

In [ ]:
massive_array[:10]

In [ ]:
%timeit sum(massive_array)# Pythods sum
%timeit np.sum(massive_array) #Numpy's sum

In [ ]:
np.mean (a2)

In [ ]:
np.max(a2)

In [ ]:
#measure of average degree to which each number is differen to the mean
np.var(a2)

In [ ]:
#measure of how spreat out a group of numbers is from the mean
np.std(a2)

In [ ]:
#std = sqrt of var
np.sqrt(np.var(a2))

In [ ]:
#Demo of std and var
high_var_array = np.array([1,100,200,300,4000,5000])
low_var_array = np.array([2,4,6,8,10])

In [ ]:
np.var(high_var_array), np.var(low_var_array)

In [ ]:
np.std(high_var_array), np.std(low_var_array)

In [ ]:
np.mean(high_var_array), np.mean(low_var_array)

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt
plt.hist(high_var_array)
plt.show()

In [ ]:
plt.hist(low_var_array)
plt.show()

In [ ]:
a2.shape

In [ ]:
##Reshape and Traspose
a2.reshape(2,3,1).shape

In [ ]:
a3.shape

In [ ]:
a2_reshape = a2.reshape(2,3,1)
a2_reshape

In [ ]:
 a3.shape

In [ ]:
a2_reshape * a3

In [ ]:
#Transpose
a2.T.shape

In [ ]:
#Dot product
np.random.seed(seed=0)
mat1 =np.random.randint(10, size=(5,3))
mat2 =np.random.randint(10, size=(5,3))

In [ ]:
mat1

In [ ]:
mat2

In [ ]:
mat1 * mat2 #element-wise multiplication

In [ ]:
mat1.shape, mat2.shape

In [ ]:
mat1.shape, mat2.T.shape #transposeit to flip inside numbers to be same

In [ ]:
mat3 =np.dot(mat1, mat2.T)

In [ ]:
mat3

In [ ]:
mat3.shape

In [ ]:
#dot product example
np.random.seed(0)
#num of items sold
sales_amounts =np.random.randint(20, size=(5,3))
sales_amounts

In [ ]:
#create a weekly sales dataframe
weekly_sales = pd.DataFrame(sales_amounts,
                           index=["Mon", "Tues","Wed","Thurs","Fri"],
                           columns=["A butter", "P butter", "C butter"] )
weekly_sales

In [ ]:
#create prices array
prices =np.array([10,8,12])
prices

In [ ]:
#create butter dataframe
butter_prices =pd.DataFrame(prices.reshape(1,3),#had to reshape since the rows and col didn't match
                           index=["Prices"],
                           columns=["A butter", "P butter", "C butter"])
butter_prices

In [ ]:
total_sales = prices.dot(sales_amount)
total_sales

In [ ]:
#shape not align and need to be transpose
total_sales = prices.dot(sales_amounts.T)
total_sales

In [91]:
butter_prices.shape, weekly_sales.T.shape

((1, 3), (3, 5))

In [94]:
#create daily sales
daily_sales = butter_prices.dot(weekly_sales.T)

In [95]:
daily_sales

Mon  Tues  Wed  Thurs  Fri
Prices  240   138  458    232  142

In [97]:
weekly_sales["Total ($)"] =daily_sales.T
weekly_sales

A butter  P butter  C butter  Total ($)
Mon          12        15         0        240
Tues          3         3         7        138
Wed           9        19        18        458
Thurs         4         6        12        232
Fri           1         6         7        142

In [98]:
###Comparision operators
a1 >a2

array([[False, False, False],
       [False, False, False]])

In [99]:
a1 <=a2

array([[ True,  True,  True],
       [ True,  True,  True]])

In [100]:
a1 ==a2

array([[ True,  True, False],
       [False, False, False]])

In [101]:
a1!=a3

array([[[False, False, False],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]])

In [107]:
##Sorting arrays
random_array = np.random.randint(10, size=(3,5))
random_array

array([[7, 8, 1, 5, 9],
       [8, 9, 4, 3, 0],
       [3, 5, 0, 2, 3]])

In [108]:
random_array.shape


(3, 5)

In [109]:
np.sort(random_array)

array([[1, 5, 7, 8, 9],
       [0, 3, 4, 8, 9],
       [0, 2, 3, 3, 5]])

In [110]:
np.argsort(random_array)

array([[2, 3, 0, 1, 4],
       [4, 3, 2, 0, 1],
       [2, 3, 0, 4, 1]])

In [115]:
np.argmax(random_array, axis=0)

array([1, 1, 1, 0, 0])

In [116]:
np.argmax(random_array, axis=1)

array([4, 1, 1])

In [120]:
np.argmin(a1)

0

In [56]:
#Numpy exercise
from matplotlib.image import imread
car =imread("car-photo.png")
print(type(car))

<class 'numpy.ndarray'>


In [57]:
car.size, car.shape

(991300, (431, 575, 4))

In [132]:
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352

In [58]:
panda =imread("panda.png")
print(type(panda))

<class 'numpy.ndarray'>


In [61]:
panda 

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0

In [ ]:
panda.sa